
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 29;
  public static final int LBRACKET = 20;
  public static final int GREATER = 36;
  public static final int LPAREN = 18;
  public static final int INT = 2;
  public static final int LESS = 35;
  public static final int MINUS = 27;
  public static final int WRITE = 24;
  public static final int RPAREN = 19;
  public static final int NOT = 30;
  public static final int SEMICOLON = 22;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int BOOL = 3;
  public static final int COMMA = 23;
  public static final int PLUS = 26;
  public static final int MULTIPLY = 28;
  public static final int ASSIGN = 39;
  public static final int LESSEQ = 37;
  public static final int IF = 9;
  public static final int ID = 13;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 21;
  public static final int EQUAL = 33;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int LCURLY = 16;
  public static final int CIN = 7;
  public static final int VOID = 4;
  public static final int RCURLY = 17;
  public static final int INTLITERAL = 14;
  public static final int ELSE = 10;
  public static final int COUT = 8;
  public static final int READ = 25;
  public static final int WHILE = 11;
  public static final int GREATEREQ = 38;
  public static final int STRINGLITERAL = 15;
  public static final int FALSE = 6;
  public static final int NOTEQ = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOL",
  "VOID",
  "TRUE",
  "FALSE",
  "CIN",
  "COUT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "WRITE",
  "READ",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUAL",
  "NOTEQ",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "ASSIGN"
  };
}

